name: DevSecOps CI

on: 
    push:
        branches: [ main ]

jobs:
    Code-Quality:
        uses: ./.github/workflows/code-lint.yml
    Secret-Scan:
        uses: ./.github/workflows/secret-scanning.yml
    Dependency-Scan:
        uses: ./.github/workflows/dependency-check.yml
    Image-Scan:
        uses: ./.github/workflows/image-scan.yml
    # Sonarqube-Scan:
    #     uses: ./.github/workflows/sonar-scan.yml
    #     secrets: inherit
    Image-Build-and-Push:
        needs: [Code-Quality, Secret-Scan, Dependency-Scan, Image-Scan ] #, Sonarqube-Scan]
        uses: ./.github/workflows/image-push.yml
        secrets: inherit