name: Image Build and Push

on:
    workflow_call:

jobs:
    Build-and-Push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            