name: Secret Scan
on:
    workflow_call:

jobs:
    Secret-Scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7
              with:
                fetch-depth: 0 # Fetches all git history to catch hidden secrets in old commits

            - name: Run TruffleHog Secret Scan
              uses: trufflesecurity/trufflehog@main
              with:
                extra_args: --fail